baseURL       = "https://atom-robotics-lab.github.io"
languageCode  = "en-us"
title         = "A.T.O.M Labs"
theme         = "roxo"
summarylength = 25
googleAnalitycsID = "G-PLG0BJF1QP"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
  
# markup
  [markup.highlight]
    style = 'friendly'
# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Wiki"
    url     = "wiki"
    weight  = 3
 [[menu.nav]]
    name    = "Projects"
    url     = "portfolio"
    weight  = 4
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 5
  # [[menu.nav]]
  # name    = "Sessions"
  # url     = "sessions"
  # weight  = 6
  [[menu.nav]]
    name    = "Downloads"
    url     = "downloads"
    weight  = 6
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 7

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "A Robotics Society | Community based out of Delhi"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/hero-background.png"
    heading               = "A.T.O.M ROBOTICS LAB"
    tagline               = "WE PLAY HARD, WE WORK HARD"
    primary_button        = "See Our Projects"
    primary_button_url    = "https://github.com/atom-robotics-lab"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

#  [params.portfolio]
#    enable    = true
#    title     = "OUR RECENT WORKS"
#    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

#  [params.call_to_action]
#    enable              = true
#    background_image    = "images/backgrounds/cta-background.jpg"
#    title               = "LET’S WORK TOGETHER"
#    primary_button      = "Submit Query"
#    primary_button_url  = "contact"
#    secondary_button    = "Not Convinced"
#    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Where to find us?"
      address = "ECE Block Basement <br>Maharaja Agrasen Institute of Technology"
      phone   = "8802327251"
      email   = "atom@inventati.org"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Us"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Discord"
          url  = "https://discord.gg/QxezpRQkJG"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/atom_robotics_"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/a.t.o.m_robotics_lab/"
        [[params.footer.social.link]]
          name = "Github"
          url  = "https://github.com/atom-robotics-lab"
        [[params.footer.social.link]]
          name = "YouTube"
          url  = "https://www.youtube.com/channel/UCMGzre9_yk8R42rBfu9gO1A"
      # Footer Service
      [params.footer.service]
        title       = "We like to build Robots:"
        description = "A Robotics Society | Community <br>based out of Delhi"